[package]
name = "rust_http_sig"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "1.1.0"
indexmap = "2.2.6"
sfv = "0.9.4"
thiserror = "1.0.58"

[lib]
